config/routes.rb
Rails.application.routes.draw do

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  #
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyappReinforcing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1> Posts </h1>
<% @posts.each do |post| %>
    <h2><%= post.title %></h2>
    <h3><%= post.author %></h3>
    <p><%= post.body %></p>
    <%= link_to 'Show post', post_path(post) %>
<% end %>

app/views/posts/new.html.erb
<h1> New Post </h1>
<%= form_for @post do |f| %>
    <%= f.label :title %>:
    <%= f.text_field :title %>

    <%= f.label :author %>
    <%= f.text_field :author %>

    <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1> Post </h1>
<h2><%= @post.title %></h2>
<h3><%= @post.author %></h3>
<p><%= @post.body %><p>
<%= link_to 'Back', posts_path %>